---
apiVersion: v1
kind: Namespace
metadata:
  name: hive
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: metastore-cfg
  namespace: hive
data:
  core-site.xml: |2-
        <configuration>
            <property>
                <name>fs.s3a.connection.ssl.enabled</name>
            <value>false</value>
            </property>
           <property>
                <name>fs.s3a.endpoint</name>
                <value>http://minio.minio.svc.cluster.local:9000</value>
            </property>
            <property>
                <name>fs.s3a.fast.upload</name>
                <value>true</value>
            </property>
            <property>
                <name>fs.s3a.access.key</name>
                <value>${env.AWS_ACCESS_KEY_ID}</value>
            </property>
            <property>
                <name>fs.s3a.secret.key</name>
                <value>${env.AWS_SECRET_ACCESS_KEY}</value>
            </property>
            <property>
                <name>fs.s3a.path.style.access</name>
                <value>true</value>
            </property>
        </configuration>
  metastore-site.xml: |2-
     <configuration>
            <property>
                <name>metastore.task.threads.always</name>
                <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask</value>
            </property>
            <property>
                <name>metastore.expression.proxy</name>
                <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
            </property>
            <property>
                <name>javax.jdo.option.ConnectionURL</name>
                <value>jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/${env.POSTGRES_DB}?allowPublicKeyRetrieval=true&amp;useSSL=false&amp;serverTimezone=UTC</value>
            </property>
            <property>
                <name>javax.jdo.option.ConnectionDriverName</name>
                <value>org.postgresql.Driver</value>
            </property>
            <property>
                <name>javax.jdo.option.ConnectionUserName</name>
                <value>${env.POSTGRES_USER}</value>
            </property>
            <property>
                <name>javax.jdo.option.ConnectionPassword</name>
                <value>${env.POSTGRES_PASSWORD}</value>
            </property>
            <property>
                <name>metastore.warehouse.dir</name>
                <value>s3a://test/warehouse</value>
            </property>
            <property>
                <name>metastore.thrift.port</name>
                <value>9083</value>
            </property>
            <property>
                <name>metastore.log4j.file</name>
                <value>/opt/metastore-log4j2.properties</value>
            </property>
        </configuration>
  
---
# same secret as in minio namespace, the minio admin account - for ease of use (s3 key/secret)
apiVersion: v1
kind: Secret
metadata:
  name: minio-admin
  namespace: hive
data:
  username: YWRtaW4= #admin
  password: YWRtaW5wYXNzd29yZDEyMw== #adminpassword123
---
#same secret that is in the postgres namespace
apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin
  namespace: hive
data:
  db: cG9zdGdyZXM= #postgres
  password: cG9zdGdyZXNzcGFzc3dvcmQxMjM= #postgresspassword123
  user: cG9zdGdyZXM= #postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-postgres-init-script
  namespace: hive
data:
  entrypoint.sh: |-
    #!/bin/bash
    /opt/apache-hive-metastore-3.1.3-bin/bin/schematool --verbose -initSchema -dbType postgres -userName $POSTGRES_USER -passWord $POSTGRES_PASSWORD -url jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/$POSTGRES_DB
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hive-initschema
  namespace: hive
spec:
  template:
    spec:
      containers:
      - name: hivemeta
        image: alexcpn/hivemetastore:3.13
        command: ["/bin/entrypoint.sh"]
        volumeMounts:
          - name: hive-postgres-init-script-volume
            mountPath: /bin/entrypoint.sh
            readOnly: true
            subPath: entrypoint.sh
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: password
      restartPolicy: Never
      volumes:
      - name: hive-postgres-init-script-volume
        configMap:
          defaultMode: 0700
          name: hive-postgres-init-script
  backoffLimit: 1
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore
  namespace: hive
spec:
  selector:
    matchLabels:
      app: metastore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metastore
    spec:
      containers:
      - name: metastore
        image: alexcpn/hivemetastore:3.1.3.5
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: password  
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-admin
              key: username
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-admin
              key: password
        ports:
        - containerPort: 9083
        volumeMounts:
        - name: metastore-cfg-vol
          mountPath: /opt/apache-hive-metastore-3.1.3-bin/conf/metastore-site.xml
          subPath: metastore-site.xml
        - name: metastore-cfg-vol
          mountPath: /opt/hadoop-3.3.0/etc/hadoop/core-site.xml
          subPath: core-site.xml
        command: ["/opt/apache-hive-metastore-3.1.3-bin/bin/start-metastore"]
        args: ["-p", "9083"]
        resources:
          requests:
            memory: "1G"
        imagePullPolicy: Always
      volumes:
      - name: metastore-cfg-vol
        configMap:
          name: metastore-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: metastore
  namespace: hive
spec:
  type: LoadBalancer
  ports:
  - port: 9083
  selector:
    app: metastore